# Generated by Django 5.2.2 on 2025-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alternatif', models.CharField(help_text='Nama alternatif cloud (e.g., AWS, Azure, GCP)', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Daftar Alternatif',
            },
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.CharField(help_text='Nama kriteria (e.g., Biaya, Kinerja)', max_length=100)),
                ('atribut', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], help_text="Tipe kriteria: 'benefit' atau 'cost'", max_length=10)),
                ('bobot', models.FloatField(default=0.0, help_text='Bobot kriteria hasil dari perhitungan AHP')),
            ],
            options={
                'verbose_name_plural': 'Daftar Kriteria',
            },
        ),
    ]
